import fs from 'node:fs/promises';
import path from 'node:path';

const ROOT='/home/dp/Desktop/soloapps/codexdesktop';
const OUT=path.join(ROOT,'hunts/2026-07-11-5/phase-0/agents/formation-feedback');
const SNAP=path.join(ROOT,'market-motion/hn/snapshots');
const RUN='2026-07-11-5-formation-feedback';
const observedAt=new Date().toISOString();
const now=Math.floor(new Date('2026-07-11T12:00:00Z').getTime()/1000), day=86400;
const windows=[['recent-30d',now-30*day,now],['prior-30d',now-60*day,now-30*day],['recent-90d',now-90*day,now],['prior-90d',now-180*day,now-90*day],['prior-year-comparable-90d',now-455*day,now-365*day]];
await fs.mkdir(OUT,{recursive:true}); await fs.mkdir(SNAP,{recursive:true});
const priorPath=path.join(ROOT,'hunts/2026-07-11-4/phase-0/agents/formation-feedback/records.jsonl');
const priorIds=new Set((await fs.readFile(priorPath,'utf8').catch(()=>'' )).trim().split('\n').filter(Boolean).map(x=>JSON.parse(x).hn?.id).filter(Boolean));
const records=[],queries=[],failures=[],seen=new Set(),storyMeta=new Map(),targets=[];
const clean=s=>s?String(s).replace(/<[^>]*>/g,' ').replace(/&quot;/g,'"').replace(/&#x27;/g,"'").replace(/&gt;/g,'>').replace(/&lt;/g,'<').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim()||null:null;
const slug=s=>String(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,90);
const domainOf=u=>{try{return new URL(u).hostname.toLowerCase().replace(/^www\./,'')}catch{return null}};
async function getJson(url,context){for(let n=1;n<=3;n++){try{const r=await fetch(url,{headers:{'User-Agent':'studio-hunt-phase0/1.0'}});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.json()}catch(e){if(n===3){failures.push({observedAt,source:'HN Algolia API',url,context,error:String(e),fallbacksAttempted:['three API retries'],status:'error'});return null}await new Promise(r=>setTimeout(r,n*600))}}}
function classify(text,isShow,isComment){const t=text||'';if(isShow&&!isComment)return {actorType:'startup_founder',actorEvidence:'Author submitted a Show HN launch.',statementType:'product_pitch',firsthand:false,classificationConfidence:'high',classificationReason:'Show HN tag and author directly establish a founder launch pitch.'};const fp=/\b(i|we|our|my)\b/i.test(t), purchase=/\b(pay|paid|bought|subscribe|subscription|cost me|spend|\$\d)\b/i.test(t), workaround=/\b(spreadsheet|script|manual|manually|workaround|copy.?paste|csv|zapier)\b/i.test(t), workflow=/\b(use|used|run|manage|handle|track|export|import|review|process|work|switched|built)\b/i.test(t), request=/\b(would|wish|need|please|missing|support|feature|integration|export|import|api)\b/i.test(t);if(fp&&(purchase||workaround||workflow))return {actorType:'buyer_operator',actorEvidence:'First-person language explicitly describes the speaker own use, purchase, implementation, or workaround.',statementType:purchase?'own_purchase':workaround?'own_workaround':'own_workflow',firsthand:true,classificationConfidence:'medium',classificationReason:`First-person pronoun co-occurs with explicit ${purchase?'purchase/spend':workaround?'manual workaround':'tool/workflow'} language in the preserved excerpt.`};return {actorType:'unknown',actorEvidence:null,statementType:request?'feature_request':'market_opinion',firsthand:false,classificationConfidence:request?'medium':'low',classificationReason:request?'Text explicitly requests or identifies a missing capability, but actor role is not established.':'No sufficiently explicit first-person workflow or purchase evidence; classification kept unknown/conservative.'}}
function add(hit,window,tag,artifactPath,storyId=null){const id=String(hit.objectID);if(seen.has(id)||priorIds.has(id))return;seen.add(id);const isComment=!!hit.comment_text,text=clean(hit.comment_text||hit.story_text||hit.title||hit.story_title),title=clean(hit.title||hit.story_title),meta=classify(text,tag==='show_hn',isComment),domain=isComment?(storyMeta.get(String(storyId))?.domain||null):domainOf(hit.url),startup=tag==='show_hn'&&title?title.replace(/^Show HN:\s*/i,'').split(/[—–:\-|]/)[0].trim().slice(0,120):null,price=text?.match(/(?:\$|USD\s?)\d[\d,.]*(?:\s*\/\s*(?:mo|month|yr|year|hour))?/i)?.[0]||null,moneyType=price?(meta.statementType==='own_purchase'?'exact_job_spend':'currency_mention'):'none';
 records.push({recordId:`hn-${isComment?'comment':'story'}-${id}`,source:'Hacker News via official Algolia API',url:isComment?`https://news.ycombinator.com/item?id=${id}`:(hit.url||`https://news.ycombinator.com/item?id=${id}`),observedAt,publishedAt:hit.created_at||null,window,sourceLane:'formation_feedback',retrievalStatus:'verified',...meta,startupName:startup,productDomain:domain,founderHandle:isComment?null:(hit.author||null),buyer:meta.actorType==='buyer_operator'?'HN speaker describing own context':null,trigger:null,input:null,repeatedAction:meta.firsthand?text?.slice(0,500):null,output:null,destination:null,frequency:text?.match(/\b(daily|weekly|monthly|every day|each day|every week|per month)\b/i)?.[0]||null,timeSpent:text?.match(/\b\d+(?:\.\d+)?\s*(minutes?|mins?|hours?|hrs?|days?)\b/i)?.[0]||null,priceOrWage:price,commercialMetric:isComment?null:{points:hit.points??0,comments:hit.num_comments??0},metricPeriod:null,currentTools:[...new Set((text?.match(/\b(Excel|Google Sheets|Sheets|Notion|Slack|Zapier|GitHub|Jira|Trello|Airtable|CSV|Python|ChatGPT)\b/gi)||[]).map(x=>x.toLowerCase()))],remainingManualWork:meta.statementType==='own_workaround'?text?.slice(0,500):null,objection:isComment&&/\b(but|however|problem|issue|missing|can't|cannot|doesn't|expensive|slow|manual|privacy|trust)\b/i.test(text||'')?text.slice(0,500):null,requestedOutcome:meta.statementType==='feature_request'?text?.slice(0,500):null,textExcerpt:text?.slice(0,1200)||null,artifactPath,independenceKey:[domain||'news.ycombinator.com',hit.author||'unknown',startup||storyId||id,'hn-algolia'].map(slug).join('|'),commercialStrength:moneyType==='exact_job_spend'?'medium':'none',moneyType,caveat:isComment?`HN comment; parent story ${storyId}; role based only on preserved speaker text.`:`${tag==='show_hn'?'Launch is supply evidence only.':'Ask HN submission.'} HN id ${id}.`,hn:{id,parentId:hit.parent_id?String(hit.parent_id):null,storyId:storyId?String(storyId):null,author:hit.author||null,title,points:hit.points??null,commentCount:hit.num_comments??null}});if(!isComment)storyMeta.set(id,{domain,tag,title});}
for(const [window,start,end] of windows)for(const tag of ['show_hn','ask_hn'])for(const page of [1,2]){const p=new URLSearchParams({tags:tag,numericFilters:`created_at_i>${start},created_at_i<${end}`,hitsPerPage:'80',page:String(page)}),url=`https://hn.algolia.com/api/v1/search_by_date?${p}`,data=await getJson(url,{window,tag,page});if(!data)continue;const artifactPath=`market-motion/hn/snapshots/${RUN}-${window}-${tag}-page-${page}.json`;await fs.writeFile(path.join(ROOT,artifactPath),JSON.stringify({observedAt,window,start,end,tag,page,response:data},null,2),{flag:'wx'}).catch(e=>{if(e.code!=='EEXIST')throw e});queries.push({observedAt,source:'HN Algolia API',window,query:`tags=${tag}; created_at_i>${start},created_at_i<${end}; page=${page}`,url,resultCount:data.hits?.length||0,totalHits:data.nbHits??null,pagesFetched:1,purpose:`rotate beyond prior page-0 coverage: ${tag==='show_hn'?'formation and persistence':'own problems and workarounds'}`,artifactPath});for(const h of data.hits||[]){add(h,window,tag,artifactPath);targets.push({id:String(h.objectID),window,tag,score:(h.num_comments||0)*2+(h.points||0)})}}
for(const t of [...new Map(targets.sort((a,b)=>b.score-a.score).map(x=>[x.id,x])).values()].slice(0,45)){const p=new URLSearchParams({tags:`comment,story_${t.id}`,hitsPerPage:'40',page:'0'}),url=`https://hn.algolia.com/api/v1/search_by_date?${p}`,data=await getJson(url,{storyId:t.id,purpose:'comment hydration'});if(!data)continue;const artifactPath=`market-motion/hn/snapshots/${RUN}-comments-story-${t.id}.json`;await fs.writeFile(path.join(ROOT,artifactPath),JSON.stringify({observedAt,target:t,response:data},null,2),{flag:'wx'}).catch(e=>{if(e.code!=='EEXIST')throw e});queries.push({observedAt,source:'HN Algolia API',window:t.window,query:`tags=comment,story_${t.id}`,url,resultCount:data.hits?.length||0,totalHits:data.nbHits??null,pagesFetched:1,purpose:'hydrate objections, integrations, trust failures, exports, approval and manual residue',artifactPath});for(const h of (data.hits||[]).filter(h=>clean(h.comment_text)?.length>=80).slice(0,12))add(h,t.window,t.tag,artifactPath,t.id)}
await fs.writeFile(path.join(OUT,'records.jsonl'),records.map(JSON.stringify).join('\n')+'\n');await fs.writeFile(path.join(OUT,'queries.jsonl'),queries.map(JSON.stringify).join('\n')+'\n');await fs.writeFile(path.join(OUT,'failures.jsonl'),failures.map(JSON.stringify).join('\n')+(failures.length?'\n':''));
const by=k=>records.reduce((a,r)=>(a[r[k]??'null']=(a[r[k]??'null']||0)+1,a),{}),dups=Object.entries(records.reduce((a,r)=>(a[r.independenceKey]=(a[r.independenceKey]||0)+1,a),{})).filter(([,n])=>n>1).map(([key,count])=>({key,count}));
const metrics={observedAt,lane:'formation_feedback',totalRecords:records.length,verifiedRecords:records.filter(r=>r.retrievalStatus==='verified').length,stories:records.filter(r=>r.recordId.includes('-story-')).length,comments:records.filter(r=>r.recordId.includes('-comment-')).length,firsthand:records.filter(r=>r.firsthand).length,qualifiedFirsthand:records.filter(r=>r.firsthand&&['medium','high'].includes(r.classificationConfidence)).length,currencyMentions:records.filter(r=>r.priceOrWage).length,qualifiedExactJobMoney:records.filter(r=>['exact_job_spend','exact_job_wage'].includes(r.moneyType)&&['medium','high'].includes(r.classificationConfidence)).length,uniqueAuthors:new Set(records.map(r=>r.hn.author).filter(Boolean)).size,uniqueProductDomains:new Set(records.map(r=>r.productDomain).filter(Boolean)).size,suspectedDuplicateIndependenceKeys:dups,bySource:by('source'),byWindow:by('window'),byActor:by('actorType'),byStatement:by('statementType'),byVerification:by('retrievalStatus'),byConfidence:by('classificationConfidence'),byMoneyType:by('moneyType'),missingFields:['productDomain','actorEvidence','buyer','trigger','input','repeatedAction','output','destination','frequency','timeSpent','priceOrWage','remainingManualWork','objection','requestedOutcome'].reduce((a,k)=>(a[k]=records.filter(r=>r[k]==null).length,a),{}),queryCount:queries.length,failureCount:failures.length,priorIdsExcluded:priorIds.size,coverageNotes:['Official HN Algolia API; pages 1-2 extend prior page-0 coverage for five required comparison windows and both Show HN and Ask HN.','Fresh high-engagement stories were comment-hydrated; records previously captured in hunt 4 were excluded.','Launches remain supply evidence; medium-confidence firsthand labels require explicit first-person plus workflow, purchase, or workaround wording.']};await fs.writeFile(path.join(OUT,'metrics.json'),JSON.stringify(metrics,null,2)+'\n');console.log(JSON.stringify(metrics,null,2));
