export const ipcChannels = {
    windowMinimize: 'window:minimize',
    windowToggleMaximize: 'window:toggleMaximize',
    windowClose: 'window:close',
    browserNewTab: 'browser:newTab',
    browserCloseTab: 'browser:closeTab',
    browserActivateTab: 'browser:activateTab',
    browserNavigate: 'browser:navigate',
    browserBack: 'browser:back',
    browserForward: 'browser:forward',
    browserReload: 'browser:reload',
    browserSetBounds: 'browser:setBounds',
    browserBeginDividerDrag: 'browser:beginDividerDrag',
    browserEndDividerDrag: 'browser:endDividerDrag',
    browserSetOverlayOpen: 'browser:setOverlayOpen',
    browserState: 'browser:state',
    codexGetAuthStatus: 'codex:getAuthStatus',
    codexListThreads: 'codex:listThreads',
    codexStartThread: 'codex:startThread',
    codexResumeThread: 'codex:resumeThread',
    codexReadThread: 'codex:readThread',
    codexSendMessage: 'codex:sendMessage',
    codexInterruptTurn: 'codex:interruptTurn',
    codexRespondApproval: 'codex:respondApproval',
    codexSetAutoApprove: 'codex:setAutoApprove',
    codexEvent: 'codex:event',
    workspacePick: 'workspace:pick'
};
